//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LazySnake.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMaps {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMaps() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LazySnake.Resources.ResourceMaps", typeof(ResourceMaps).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;map width=&quot;10&quot; height=&quot;10&quot;&gt;
        ///  &lt;vertex posX=&quot;0&quot; posxY=&quot;0&quot;&gt;0&lt;/vertex&gt;
        ///  &lt;vertex posX=&quot;1&quot; posxY=&quot;0&quot;&gt;0&lt;/vertex&gt;
        ///  &lt;vertex posX=&quot;2&quot; posxY=&quot;0&quot;&gt;0&lt;/vertex&gt;
        ///  &lt;vertex posX=&quot;3&quot; posxY=&quot;0&quot;&gt;0&lt;/vertex&gt;
        ///  &lt;vertex posX=&quot;4&quot; posxY=&quot;0&quot;&gt;0&lt;/vertex&gt;
        ///  &lt;vertex posX=&quot;5&quot; posxY=&quot;0&quot;&gt;0&lt;/vertex&gt;
        ///  &lt;vertex posX=&quot;6&quot; posxY=&quot;0&quot;&gt;0&lt;/vertex&gt;
        ///  &lt;vertex posX=&quot;7&quot; posxY=&quot;0&quot;&gt;0&lt;/vertex&gt;
        ///  &lt;vertex posX=&quot;8&quot; posxY=&quot;0&quot;&gt;0&lt;/vertex&gt;
        ///  &lt;vertex posX=&quot;9&quot; posxY=&quot;0&quot;&gt;0&lt;/vertex&gt;
        ///  
        ///  &lt;vertex posX=&quot;0&quot; posxY=&quot;1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Map01 {
            get {
                return ResourceManager.GetString("Map01", resourceCulture);
            }
        }
    }
}
